# create new post
POST http://localhost:3000/api/post/create HTTP/1.1
Content-Type: application/json

{
  "type": "text",
  "authorId": "658170cbb954e9f5b905cc02",
  "title": "Seriojodf",
  "textPostText": ".........",
  "tags": "123 456"
}

###
#update post
PATCH http://localhost:3000/api/post/6661358d-bbe8-4f5b-9d5e-4ac5072cbdc4 HTTP/1.1
Content-Type: application/json

{
  "likesCount": 3
}

###
#delete post
DELETE http://localhost:3000/api/post/3c1b663a-be22-41c7-b5de-3c909a53eb11 HTTP/1.1


###
# get posts
GET http://localhost:3000/api/post/ HTTP/1.1

###
#get post details
GET http://localhost:3000/api/post/6d308040-96a2-4162-bea6-2338e9976501 HTTP/1.1
Content-Type: application/json

###
# find post by title
GET http://localhost:3000/api/post/find-by-title HTTP/1.1
Content-Type: application/json

{
  "title": "Seriojodf"
}

###
#set like for post

PATCH http://localhost:3000/api/post/6661358d-bbe8-4f5b-9d5e-4ac5072cbdc4/set-like HTTP/1.1

###
#remove like for post
PATCH http://localhost:3000/api/post/6661358d-bbe8-4f5b-9d5e-4ac5072cbdc4/remove-like HTTP/1.1

###
#repost
POST http://localhost:3000/api/post/dsdsdsd/repost
Content-Type: application/json

{
  "userId": "658170cbb954e9f5b905cc02"
}


###
# get comments for post
GET http://localhost:3000/api/post/6d308040-96a2-4162-bea6-2338e9976501/comments?page=2 HTTP/1.1

###
# create new comment
POST http://localhost:3000/api/post/eecc028c-2cb2-4833-b744-1a682af3c2c2/create-comment HTTP/1.1
Content-Type: application/json

{
  "text": "New comment",
  "author": "1a682af3c2c2-b744-4833-2cb2-eecc028c"
}

###
# delete comment
DELETE http://localhost:3000/api/post/eecc028c-2cb2-4833-b744-1a682af3c2c2/delete-comment/1a682af3c2c2 HTTP/1.1
Content-Type: application/json

{
  "authorId": "1a682af3c2c2-b744-4833-2cb2-eecc028c"
}
