# Get all comments for post
GET http://localhost:3000/api/posts/6d308040-96a2-4162-bea6-2338e9976502/comments?limit=1&page=1 HTTP/1.1

###
# Create a new comment for post
POST http://localhost:3000/api/posts/6d308040-96a2-4162-bea6-2338e9976501/comments HTTP/1.1
Content-Type: application/json

{
  "text": "Test comment for blogPostService",
  "authorId": "658170cbb954e9f5b905ccf4"
}

###
# Delete comment
DELETE http://localhost:3000/api/posts/a3fd134c-2db7-48fd-83b0-3fa95e32a9a8/comments HTTP/1.1
Content-Type: application/json

{
  "authorId": "658170cbb954e9f5b905ccf4"
}
